# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm # or mongodb or phpcr

  mappings:
    uploads_files:
      uri_prefix: '%app.path.uploads_files%'
      upload_destination: '%kernel.project_dir%/public%app.path.uploads_files%'

      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true