vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        docs_thumbnails:
            uri_prefix: '%uploads_path%'
            # upload_destination: '%kernel.project_dir%/public/%uploads_path%'
            upload_destination: default.storage
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # delete_on_update: false
            # delete_on_remove: true
