vich_uploader:
    db_driver: orm

    mappings:
        recipisses_path:
            #uri_prefix: '%app.path.uploads_recipisses%'
            uri_prefix: /uploads/recipisses
            upload_destination: '%kernel.project_dir%/public/uploads/recipisses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true