vich_uploader:
    db_driver: orm
    #storage: flysystem

    mappings:
        recipisses_load:
            # uri_prefix: tousrecipisses
            uri_prefix: '%app.path.uploads_recipisses%'
            # upload_destination: '%kernel.project_dir%/public/tousrecipisses'
            upload_destination: '%kernel.project_dir%/public%app.path.uploads_recipisses%' # Use the name you defined for your storage here '%kernel.project_dir%/public/tousrecipisses'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' } # supposing that the object contains a "slug" attribute or a "getSlug" method