app_login :
    path: /
    controller: App\Controller\SecurityController::login
# homepage:
#     path: /{_locale}
#     controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#     requirements:
#         _locale: '%app_locales%'
#     defaults:
#         template: security/login.html.twig
#         _locale: '%locale%'